create table user (
    id bigint generated by default as identity (start with 1),
    active boolean,
    email varchar(255),
    password varchar(255),
    username varchar(255) not null,
    primary key (id)
);

create table user_role (
    user_id bigint not null,
    role varchar(255)
);